# Generated by Django 5.2.10 on 2026-01-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_app', '0005_alertsetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertsetting',
            old_name='enabled',
            new_name='expense_alert_enabled',
        ),
        migrations.AddField(
            model_name='alertsetting',
            name='income_alert_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alertsetting',
            name='payable_alert_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alertsetting',
            name='receivable_alert_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
