# Generated by Django 5.2.10 on 2026-01-15 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_app', '0006_rename_enabled_alertsetting_expense_alert_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
        migrations.RemoveField(
            model_name='income',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='income',
            name='user',
        ),
        migrations.DeleteModel(
            name='Categorys',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
