# Generated by Django 6.0.1 on 2026-02-25 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_app', '0007_remove_expense_category_remove_expense_payment_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseTrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_key', models.CharField(max_length=50)),
                ('total_expense', models.DecimalField(decimal_places=2, max_digits=15)),
                ('growth', models.FloatField(default=1.0)),
            ],
            options={
                'db_table': 'expense_training_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncomeTrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_key', models.CharField(max_length=50)),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('growth', models.FloatField(default=1.0)),
            ],
            options={
                'db_table': 'income_training_data',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='alert',
            options={},
        ),
        migrations.RemoveField(
            model_name='alert',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='alertsetting',
            name='payable_alert_enabled',
        ),
        migrations.RemoveField(
            model_name='alertsetting',
            name='receivable_alert_enabled',
        ),
        migrations.RemoveField(
            model_name='payable',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='receivable',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='settings',
            name='alert_threshold_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='settings',
            name='forecast_duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='settings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CashFlowForecast',
        ),
    ]
