# Generated by Django 6.0.1 on 2026-02-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_app', '0008_expensetrainingdata_incometrainingdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
