# Generated by Django 6.0.1 on 2026-02-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_app', '0009_alert_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='temp_fix',
            field=models.BooleanField(default=False),
        ),
    ]
