# Generated by Django 6.0.1 on 2026-02-25 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_app', '0010_alert_is_read_alert_temp_fix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='temp_fix',
        ),
    ]
